### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by mimccio** [mimccio/komi#5]
- [x] Create Project in CircleCI UI
- [x] Create a config.yml in .circleci folder
```yml
version: 2

jobs:
  build:
    docker:
      # the Docker image with Cypress preinstalled
      - image: cypress/internal:cy-0.19.2
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Running Unit tests
          command: yarn test
      - run:
          name: Running Cypress E2E and integration tests
          command: cypress run --reporter junit --reporter-options "mochaFile=results/my-test-output.xml"
      - store_test_results:
          path: results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots  
      - run:
          name: Create build if tests pass and branch is Master or Develop
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build
            else
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                npm run build
              else
                echo "Not master branch so not creating build"
              fi
            fi
      - deploy:
          name: Deploy branch Master or Develop (komi-dev)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./node_modules/.bin/surge --project ./build --domain komi-apollo.surge.sh
            else
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                ./node_modules/.bin/surge --project ./build --domain komi-apollo-dev.surge.sh
              else
                echo "Not master branch so not deploying"
              fi
            fi
```

- [x] Add a 200 page for surge client side routing

in package.json
```yml
"scripts": {
    "build": "node scripts/build.js && cp build/index.html build/200.html",
  },
```
- [x] `yarn add --dev surge`
